//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impendulo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurriculumCourseEnrollment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CurriculumCourseEnrollment()
        {
            this.Schedules = new ObservableListSource<Schedule>();
        }
    
        public int CurriculumCourseEnrollmentID { get; set; }
        public int CurriculumCourseID { get; set; }
        public int EnrollmentID { get; set; }
        public bool Excempt { get; set; }
        public decimal CourseCost { get; set; }
    
        public virtual CurriculumCourse CurriculumCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Schedule> Schedules { get; set; }
        public virtual Enrollment Enrollment { get; set; }
    }
}
