//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impendulo.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.Companies = new ObservableListSource<Company>();
            this.Venues = new ObservableListSource<Venue>();
        }
    
        public int ScheduleID { get; set; }
        public int CurriculumCourseEnrollmentID { get; set; }
        public System.DateTime ScheduleStartDate { get; set; }
        public System.DateTime ScheduleCompletionDate { get; set; }
        public int EnrollmentID { get; set; }
        public int IndividualID { get; set; }
    
        public virtual CurriculumCourseEnrollment CurriculumCourseEnrollment { get; set; }
        public virtual Enrollment Enrollment { get; set; }
        public virtual Facilitator Facilitator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Company> Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Venue> Venues { get; set; }
    }
}
